
version: '3.7'

services:

  docker_bot:
    container_name: docker_bot
    build: ./bot

    restart: on-failure
    environment:
      BOT_TOKEN: "6102261529:AAGZPmItrh8oXrdaMO58xCeXwXc4qCX-FYc"
      DATABASE_URL: "postgresql+psycopg2://postgres:password@db:5432/mydatabase"
#    depends_on:
#      - db
#  db:
#    image: postgres:16-alpine
#    restart: always
#    environment:
#      POSTGRES_PASSWORD: password
#      POSTGRES_DB: mydatabase
#    volumes:
#      - docker_testdb-data:/var/lib/postgresql/data

#volumes:
#  docker_testdb-data: